# Generated by Django 4.1.2 on 2022-11-25 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Enter tournament name', max_length=100)),
                ('description', models.TextField(help_text='Enter description tournament', max_length=200)),
                ('logo', models.ImageField(default='default_logos/tournament_default.png', upload_to='tournaments_logo')),
                ('teams_number', models.IntegerField(default=2)),
                ('players_in_team', models.IntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Enter team name', max_length=100)),
                ('logo', models.ImageField(default='default_logos/team_default.png', upload_to='team_logo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Your bio', max_length=100, null=True)),
                ('avatar', models.ImageField(blank=True, default='default_logos/player_default.png', upload_to='players_avatar')),
                ('teams', models.ManyToManyField(blank=True, to='main.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blue_score', models.IntegerField(default=0)),
                ('red_score', models.IntegerField(default=0)),
                ('blue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue', to='main.team')),
                ('red', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red', to='main.team')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.round')),
            ],
        ),
    ]
