# Generated by Django 4.1.1 on 2022-10-09 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='attending',
            new_name='tournament',
        ),
        migrations.RemoveField(
            model_name='team',
            name='owner',
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(default='none', upload_to=''),
        ),
        migrations.AddField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(default='none', upload_to=''),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(through='main.Player', to=settings.AUTH_USER_MODEL),
        ),
    ]
