# Generated by Django 4.1.2 on 2022-11-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_round_reward_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='approved_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
