# Generated by Django 4.1.2 on 2022-11-27 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_player_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='round',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='bracket_exists',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='blue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blue', to='main.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='red', to='main.team'),
        ),
    ]
