# Generated by Django 4.1.3 on 2022-11-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_match_finished_round_finished_team_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='wins_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='wins_tournament',
            field=models.IntegerField(default=0),
        ),
    ]
