# Generated by Django 4.1.2 on 2022-10-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_player_teams_remove_team_players_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='enrollments',
            field=models.ManyToManyField(to='main.team'),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
