# Generated by Django 4.1.2 on 2022-10-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_player_enrollments_delete_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='enrollments',
        ),
        migrations.AddField(
            model_name='player',
            name='teams',
            field=models.ManyToManyField(blank=True, to='main.team'),
        ),
    ]
