# Generated by Django 4.1.2 on 2022-10-10 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_player_enrollments_player_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blue_score', models.IntegerField(default=0)),
                ('red_score', models.IntegerField(default=0)),
                ('blue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue', to='main.team')),
                ('red', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red', to='main.team')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.round')),
            ],
        ),
    ]
