# Generated by Django 4.1.2 on 2022-11-29 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tournament_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='date_of_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 1, 3, 29, 266904)),
        ),
    ]
