# Generated by Django 4.1.2 on 2022-10-14 13:13

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_round_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(default='none', upload_to=pathlib.PurePosixPath('/Users/mkoval/VScodeProjects/Student-tournaments2.0/webapp/src/media/team_logo')),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(default='none', upload_to=pathlib.PurePosixPath('/Users/mkoval/VScodeProjects/Student-tournaments2.0/webapp/src/media/tournaments_logo')),
        ),
    ]
