# Generated by Django 4.1.2 on 2022-10-14 14:37

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_tournament_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='logo',
            field=models.ImageField(default='default_logos/tournament_default.png', upload_to=pathlib.PurePosixPath('/Users/mkoval/VScodeProjects/Student-tournaments2.0/webapp/src/media/tournaments_logo')),
        ),
    ]
