# Generated by Django 4.1.2 on 2022-10-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_team_owner_alter_tournament_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='players_in_team',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tournament',
            name='teams_number',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(default='default_logos/team_default.png', upload_to='team_logo'),
        ),
    ]
