# Generated by Django 4.1.2 on 2022-10-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_tournament_players_in_team_tournament_teams_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.ImageField(default='default_logos/player_default.png', upload_to='players_avatar'),
        ),
        migrations.AddField(
            model_name='player',
            name='bio',
            field=models.TextField(help_text='Your bio', max_length=100, null=True),
        ),
    ]
