# Generated by Django 4.1.2 on 2022-10-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_player_avatar_player_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, default='default_logos/player_default.png', upload_to='players_avatar'),
        ),
        migrations.AlterField(
            model_name='player',
            name='bio',
            field=models.TextField(blank=True, help_text='Your bio', max_length=100, null=True),
        ),
    ]
